### ISSUE TITLE
Install with --target fails

### ISSUE THREAD

**Issue by gergnz** [anjishnu/ask-alexa-pykit#19]
```
pip install --target Scratch/dev/alexa/simplesms/ ask-alexa-pykit
Collecting ask-alexa-pykit
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 512, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 276, in populate_link
    self.link = self._wheel_cache.cached_wheel(self.link, self.name)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 68, in cached_wheel
    self._cache_dir, link, self._format_control, package_name)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 137, in cached_wheel
    wheel = Wheel(wheel_name)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 637, in __init__
    self.pyversions = wheel_info.group('pyver').split('.')
AttributeError: 'NoneType' object has no attribute 'split'
```

Instead passing install-purelib via install-option works:

```
pip install --install-option="--install-purelib=Scratch/dev/alexa/simplesms" ask-alexa-pykit
```

**Comment by anjishnu** [comment]
What platform/python/pip version is this - I can't replicate this.

**Comment by gergnz** [comment]
Ubuntu 16.04 x86_64, package installs.

I tried removing packaged pip and upgrading to 8.1.2 pip, but no luck.

```
:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:    16.04
Codename:   xenial
:~$ pip --version
pytpip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
:~$ python --version
Python 2.7.11+
:~$ which pip
/usr/bin/pip
:~$ which python
/usr/bin/python
:~$ dpkg -S /usr/bin/python
python-minimal: /usr/bin/python
:~$ dpkg -S /usr/bin/pip
python-pip: /usr/bin/pip
```

**Comment by anjishnu** [comment]
Interesting I'll see if I can get my hands on a 16.04 machine on AWS or something.
